simple_flex_scan:	simple_flex_scan.l simple_flex_scan.c
					flex -o simple_flex_scan.c simple_flex_scan.l
					gcc -o simple_flex_scan simple_flex_scan.c -ll

clean:	
					rm simple_flex_scan simple_flex_scan.c
