read_several_files:	read_several_files.c read_several_files.l
					flex -o read_several_files.c read_several_files.l
					gcc -o read_several_files read_several_files.c -ll

clean:
					rm read_several_files read_several_files.c
